### ISSUE TITLE
Update artifactId, groupId and Danta dependencies

### ISSUE THREAD

**Issue by jbarrera-xumak** [DantaFramework/AEMDemo#16]
Artifacts Id for Danta projects were changed from "Danta" to "io.tikaltechnologies.danta", It needs to be updated for this project too.
Groups Id also were changed to lowercase, I think for this project we can use "aem-demo".
Also is needed to change the Danta dependencies on the POMs to use those with the new artifactsId and groupId.

**Comment by jjankowiak-xumak** [comment]
This issue is also resolved by PR #27
